version: 2
jobs:
  build:
    working_directory: ~/fleet
    docker:
      - image: electronuserland/electron-builder:wine
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn
      - run: yarn run build
      - run: yarn run pack
      - save_cache:
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
            - "~/.cache/yarn"
      - run: rm -r dist/*-unpacked dist/mac
      - store_artifacts:
          path: ~/fleet/dist/
          destination: packages
      - run: yarn test
